### ISSUE TITLE
confirmation needed from Volker Springel to release N-GenIC or S-GenIC under MIT 3-clause licence

### ISSUE THREAD

**Issue by broukema** [sbird/S-GenIC#2]
Hi Simeon. 

N-GenIC 0.03 from https://wwwmpa.mpa-garching.mpg.de/gadget/n-genic.tar.gz
with the md5sum
````
md5sumn-genic.tar.gz
ad940e3b296a1c518412bb42cc5154a2  n-genic.tar.gz
````
is non-free software. The licence says

````
written by:   Volker Springel, MPA, (c) 2003
````

with nothing extra, which means that modifying, distributing or redistributing modified copies
is forbidden under standard copyright (e.g. as per the Berne convention). See
https://en.wikipedia.org/wiki/Software_license
for a discussion on software licences.

Volker is the author, so he can authorise exceptions to his existing default copyright.
The Gadget web page does invite the reader to download N-GenIC, but it doesn't
give the reader the right to modify it, redistribute it, or redistribute modified versions.

You have given the Expat licence (aka "MIT licence", but that's ambiguous) - see
e.g. https://www.gnu.org/licenses/license-list.html#Expat to S-GenIC. 
Could you please confirm that you have authorisation from Volker to release
your modification under the Expat licence? Guessing people's intentions on the internet,
even within the cosmology community, can be a bit risky, so it would be safer to have
a proper statement from Volker. E.g. something like

````
I agree for you to licence S-GenIC under the Expat licence.
````

or

````
I authorise N-GenIC 
(md5sum: ad940e3b296a1c518412bb42cc5154a2  n-genic.tar.gz)
to be copied under the conditions of the Expat licence.
````

The simplest thing would be for him to post a message under
this issue to say that he agrees.

Thanks
Boud

**Comment by sbird** [comment]
I believe I do have permission to modify and redistribute this from Volker - not from the Gadget website, but in a private email of over a decade ago. Is there a particular reason why it is important to you to have explicit re-confirmation of this?

Although my modifications are licensed as specified in the LICENSE file it's my understanding that as long as S-GenIC uses the GSL it becomes a derived work of that and thus is overall subject to the GPL v3. I licensed it Expat so that you can, if you so desire, remove the GSL dependency and relicense it more liberally. This may apply to the original N-GenIC as well if it also has a GSL dependence.

**Comment by broukema** [comment]
hi Simeon

> I believe I do have permission to modify and redistribute this
> from Volker - not from the Gadget website, but in a private
> email of over a decade ago.

Good. :) Your public statement (here) that you have permission
from Volker is sufficient for me, and, I expect, anyone else who would want
to use your fork.

> Is there a particular reason why it is important to you to have
> explicit re-confirmation of this?

Particular reason: ["once bitten, twice shy"](https://en.wiktionary.org/wiki/once_bitten,_twice_shy) - in terms of a very widely used
cosmology package some years ago. (The link is for non-native English speakers.)

> Although my modifications are licensed as specified in the
> LICENSE file it's my understanding that as long as S-GenIC uses
> the GSL it becomes a derived work of that and thus is overall
> subject to the GPL v3. I licensed it Expat so that you can, if
> you so desire, remove the GSL dependency and relicense it more
> liberally. This may apply to the original N-GenIC as well if it
> also has a GSL dependence.

I didn't notice that. You could be right that the GSL dependence of the
2003 version of N-GenIC (md5sum above) also forces N-GenIC to
be implicitly GPL'd. Though I'm not a lawyer, just a cosmologist
wanting to avoid investing my and my students' and other colleagues' 
software time and then having to throw it away (or worse).

Thanks for this clarification - it should be enough for anyone who
wants to be careful about licences.

Cheers
Boud

**Comment by sbird** [comment]
Glad to hear that's enough! Indeed it's always sensible to be careful (and I am no lawyer either). As a side-note, if you are interested in a free-software version of Gadget beyond Gadget-2, we also have [MP-Gadget](https://github.com/MP-Gadget/MP-Gadget) all files of which are GPL, excepting cooling.c which is undetermined but probably fine (since it's also in GPLd Enzo).

**Comment by broukema** [comment]
OK, thanks for the tip. I did worry that with Gadget-3 still being developed "privately",
using the official Gadget-2 might risk having to rediscover bugs that others have already
sorted out. Recently I've been using [mpgrafic](https://tracker.debian.org/mpgrafic), which 
[compiles and passes a regression test](https://buildd.debian.org/status/package.php?p=mpgrafic) on 22 of the 
supported and unsupported 24 Debian architectures, and a [fork of RAMSES](https://bitbucket.org/broukema/ramses-use-mpif08) that was last matched
to the rteyssier branch about a year ago, plus a [front end](https://bitbucket.org/broukema/ramses-scalav) for
calling [inhomog](https://bitbucket.org/broukema/inhomog) for the relativistic Zel'dovich approximation.

Anyway, it's good to know we have at least two free-licensed initial conditions generators - 
mpgrafic + S-GenIC (and probably, implicitly via GSL, N-GenIC).

**Comment by sbird** [comment]
Yes, regression tests are very useful! I wrote some unit tests for MP-Gadget, but we still need more of them. If you feel like joining forces with us you would be very welcome.

**Comment by broukema** [comment]
I don't like making promises of software development that I *might* do. But knowing that
a project is active with friendly developers is certainly encouraging. :)
If I find the time to do something, you'll notice in the obvious places. :)

**Comment by sbird** [comment]
I couldn't ask for more than that!
